version: '3.7'
services: 
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: 'simtest-app'
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
  db:
    image: mysql:8.0
    restart: always
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'simtest-db'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - ./db:/var/lib/mysql
