apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: simtest-app
  labels:
    app: simtest-app
spec:
  source:
    type: Git
    git:
      uri: https://github.com/jfkoga/sim.git
    contextDir: httpd-hello-world
  strategy:
    type: Docker                      
    dockerStrategy:
      dockerfilePath: Dockerfile    # Look for Dockerfile in: gitUri/contextDir/dockerfilePath
  output:
    to:
      kind: ImageStreamTag
      name: simtest-app:latest
