apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    CodiAplicacio: "0615"
    CodiEntitat: ENS
    CodiInap: XXX
    CodiServei: "7_XXXX"
    Entorn: PRE
    app: simtest-app
  name: simtest-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: simtest-app
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/suport-tecdigitals-dev/simtest-app:1.0.1
          name: simtest-app
          imagePullPolicy: Always
          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: simtest-app
                  key: app.env
            - name: APP_KEY
              valueFrom:
                configMapKeyRef:
                  name: simtest-app
                  key: app.key
            - name: APP_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: simtest-app
                  key: app.debug
            - name: APP_URL
              valueFrom:
                configMapKeyRef:
                  name: simtest-app
                  key: app.url
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: simtest-app
                  key: database.host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: simtest-app
                  key: database.port
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: simtest-db
                  key: database-name
            - name: DB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: simtest-db
                  key: database-name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: simtest-db
                  key: database-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: simtest-db
                  key: database-password
          ports:
            - containerPort: 1080
              protocol: TCP
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 256Mi

