apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    CodiAplicacio: "0615"
    CodiEntitat: ENS
    CodiInap: XXX
    CodiServei: "7_XXXX"
    Entorn: PRE
    app: ${NAME}
  name: ${NAME}
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: ${NAME}
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/xxxxx-0615-xxx-pre-xxx/laravel-app:1.0.0
          name: laravel-app
          imagePullPolicy: Always
          env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: laravel-config
                  key: app.name
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: laravel-config
                  key: app.env
            - name: APP_KEY
              valueFrom:
                configMapKeyRef:
                  name: laravel-config
                  key: app.key
            - name: APP_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: laravel-config
                  key: app.debug
            - name: APP_URL
              valueFrom:
                configMapKeyRef:
                  name: laravel-config
                  key: app.url
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: db.host
            - name: DB_DATABASE
                valueFrom:
                  secretKeyRef:
                    name: db-config
                    key: db.database
            - name: DB_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: db-config
                    key: db.username
            - name: DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: db-config
                    key: db.password
          ports:
            - containerPort: 1080
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 1080
            initialDelaySeconds: 100
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            tcpSocket:
              port: 1080
            initialDelaySeconds: 120
            periodSeconds: 30
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 256Mi
        resources:
          limits:
            memory: 256Mi
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - atc-app
        from:
          kind: ImageStreamTag
          name: image-registry.openshift-image-registry.svc:5000/71018-2692-ies-pre-intra/atc-app:1.1.8
    type: ImageChange